### ISSUE TITLE
Initial State and Metadata event value

### ISSUE THREAD

**Issue by Ghost-017** [cheebeez/radio_player#1]
It would be great if RadioPlayer has a property or method that lets me get the current state of the radio. The same goes, especially for metadata.

**Comment by Ghost-017** [comment]
I have two screens, a home screen, and a radio screen. If I hit play on the radio screen, then, go back to the home screen and then, go back again to the radio screen, I have no way of telling if the radio is currently playing or not.

**Comment by cheebeez** [comment]
I think I will add this feature in the next version.

**Comment by maendamedia** [comment]
Is this already implemented? I have same issue as TS
