### ISSUE TITLE
Package  Discontinued?

### ISSUE THREAD

**Issue by Froxz** [cheebeez/radio_player#1]
Is this package  Discontinued https://pub.dev/packages/radio_player?

**Comment by cheebeez** [comment]
Hi,

It's just that the plugin is no longer distributed under the MIT license, future versions will be under copyright.

Sincerely,
Ilya Chirkunov

**Comment by Froxz** [comment]
So prior v1.0.0, we can still use it? and v1.0.0 will require subscription/payment?

**Comment by cheebeez** [comment]
Last MIT version is 0.6.0, future versions you can't resell, but I don't mind if you use them in your personal projects.

**Comment by Froxz** [comment]
Ok thank you @cheebeez and thanks for the package 👍
