### ISSUE TITLE
flush sound

### ISSUE THREAD

**Issue by paulobreim** [cheebeez/radio_player#11]
final RadioPlayer _radioPlayer = RadioPlayer();

void initRadioPlayer(BuildContext context, String url) {
 _radioPlayer.setMediaItem('Radio Player',url,);
}
  
initRadioPlayer(context,'https://xxxxx); //ok until here for the first sound
_radioPlayer.play(); // ok until here, start play
.....// wait some time
_radioPlayer.pause(); // ok until here, stop to play
initRadioPlayer(context,'https://yyyy);  //ok until here for the second sound
_radioPlayer.play(); // ok but I can hear about half second of the first sound

How I can flush the last sound

**Comment by cheebeez** [comment]
Checked on both Android 12 and iOS 14, I was unable to reproduce this bug.

**Comment by paulobreim** [comment]
ok, If I play and pause and play again without change the mp3, works well, but if after de pause i change the mp3 using the _radioPlayer.setMediaItem, when I call play, I ear something of the previous mp3.

**Comment by cheebeez** [comment]
Can you please tell me OS version, i will fix this bug if i can reproduce it.

**Comment by paulobreim** [comment]
sure!
I am using the emulator pixel 2 api 27w with android 8.1.0 and in my mobile, samsung 10e android 11

**Comment by cheebeez** [comment]
I reproduced this...

setMediaItem is async method, this means that if you change the channel and play it at the same time, the second will happen faster.
In this case, just await for the channel change.

```
SizedBox(height: 20),
TextButton(
  onPressed: () async {
    await _radioPlayer.setMediaItem(
        'Radio Player',
        'https://icecast.omroep.nl/radio1-bb-mp3',
        'assets/cover.jpg');
    _radioPlayer.play();
  },
  child: Text('Change channel'),
)
```

**Comment by paulobreim** [comment]
Excellent !!!!!!!!
work fine !

**Comment by paulobreim** [comment]
very good support
