### ISSUE TITLE
Artwork does not change on iOS lock screen

### ISSUE THREAD

**Issue by TridentTechchnolabs** [cheebeez/radio_player#15]
While the radio is playing, all works good. I get all meta data from the stream and able to display it on screen. But when I lock the screen, it shows only the default image on lock screen player. The song and artist name is displayed correctly, only has issue with image.
 It works perfectly on android though.

**Comment by cheebeez** [comment]
Ran `example/main.dart` on iPhone X (iOS 15) in debug mode.
Pressed the play button and locked the screen.
Cover changes as expected 🤔

**Comment by TridentTechchnolabs** [comment]
Thanks for the response. Even in the example file, when I add my radio url, it works good in android, but for ios, it is not working. For android the artwork image and lock screen both come perfect but in ios its not.

**Comment by TridentTechchnolabs** [comment]
I am on version 0.3.1 ( Latest ).

**Comment by cheebeez** [comment]
Can you please send me the streaming URL?

**Comment by TridentTechchnolabs** [comment]
http://hemnos.cdnstream.com/1113_48

**Comment by cheebeez** [comment]
Tested it on the iPhone X iOS 15 works as expected.

**Comment by TridentTechchnolabs** [comment]
I copied it in your example code and then tried. I don’t know why but it
showed the artwork inside app but not on Lock Screen. Metadata like artist
name and song name changed but not the image

**Comment by cheebeez** [comment]
Now I see the issue.

**Comment by cheebeez** [comment]
I can't fix it because your the stream is no longer available.

**Comment by cheebeez** [comment]
The issue is that you have a space at the end of the metadata.
[Gary Hobbs - Amame Y Besame - https://hottejano.live/nowplaying/images/default.png ]

I'm amazed that the plugin can handle this kind of data since usually, the URL is passed separately.
Improved in version 0.3.2

**Comment by TridentTechchnolabs** [comment]
So you means it’s fixed in new update?

**Comment by cheebeez** [comment]
Yes, I've added metadata trimming.

**Comment by TridentTechchnolabs** [comment]
Thanks. Will check and revert. Heartily thanks for your help..!!

**Comment by TridentTechchnolabs** [comment]
Thanks a ton for the quick solution. It worked great. I had the radio player bit customised and this update fixed the issue for me as well. Will highly recommend you player to everyone. 

Thanks again
