### ISSUE TITLE
Get stream buffer status

### ISSUE THREAD

**Issue by maendamedia** [cheebeez/radio_player#16]
Is there a way to get the stream buffer status to show a spinner if it starting up?

**Comment by cheebeez** [comment]
Only State Event.

**Comment by maendamedia** [comment]
So ot can not show buffering info? Or loading state?

**Comment by sumithkrishnank** [comment]
can we avoid buffering ? means after interruptions now buffering coming. can we avoid buffering ? what is the option to avoid buffering?
