### ISSUE TITLE
Missing stop button in notification panel

### ISSUE THREAD

**Issue by priyesh-bit** [cheebeez/radio_player#17]
The notification panel is working very fine, can anybody please show me how to add a stop button?

**Comment by priyesh-bit** [comment]
@cheebeez can you please have a look?

**Comment by cheebeez** [comment]
Hi, 

You can try adding the line "setUseStopAction(true)" next to the "setUsePlayPauseActions(true)" in "radio_player/android/src/main/kotlin/com/cheebeez/radio_player/RadioPlayerService.kt"

**Comment by priyesh-bit** [comment]
Working now, this point is missing in the README file. Better you can update README or you can allow users to customize the notification panel. :). Btw Greate work.

**Comment by priyesh-bit** [comment]
@cheebeez  can you also help me to handle the stop event from the notification panel. If I'm stopping radio player from notification then I need to refresh UI.

**Comment by cheebeez** [comment]
Stop feature is not yet supported by the plugin, but you can fork the project and make the logic yourself.

**Comment by priyesh-bit** [comment]
Okay 👍🏼
