### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Vasajj** [cheebeez/radio_player#18]
Running Gradle task 'assembleDebug'...
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\radio_player-0.4.2\android\src\main\kotlin\com\cheebeez\radio_player\RadioPlayerPlugin.kt: (103, 38): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type kotlin.collections.ArrayList<String>? /* = java.util.ArrayList<String>? */
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\radio_player-0.4.2\android\src\main\kotlin\com\cheebeez\radio_player\RadioPlayerPlugin.kt: (103, 47): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type kotlin.collections.ArrayList<String>? /* = java.util.ArrayList<String>? */
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\radio_player-0.4.2\android\src\main\kotlin\com\cheebeez\radio_player\RadioPlayerPlugin.kt: (116, 37): Type mismatch: inferred type is kotlin.collections.ArrayList<String>? /* = java.util.ArrayList<String>? */ but kotlin.collections.ArrayList<String> /* = java.util.ArrayList<String> */ was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':radio_player:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by cheebeez** [comment]
Could you please provide “flutter doctor -v” output?

**Comment by cheebeez** [comment]
Please check new version 0.4.3

**Comment by Vasajj** [comment]
Yes. After updating the version everything works. Fine. Thank you for posting updates so quickly!
