### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by TuupleMasterAndroid** [cheebeez/radio_player#19]
I add this to my app now app is not running on API level 32 some phone. Customer report this issue. 
Please add progress bar during reading stream on first time it takes about 20 seconds.

**Comment by cheebeez** [comment]
> I add this to my app now app is not running on API level 32 some phone. Customer report this issue. 
Please find out what kind of phone, this is necessary to reproduce this issue and then fix it.

>Please add progress bar during reading stream on first time it takes about 20 seconds.
As soon as the stream is loaded, the status changes, so you can display any progress bar based on that.
Here it is necessary to understand why it takes so long.

**Comment by TuupleMasterAndroid** [comment]
thanks for your quick response.
As per you request customer report me Xiaomi 11 Lite NE 5G, realme X7 Max 5G, iQOO Z6 5G.
Xiaomi 11 Lite & RealMe X7 App launch but not run the app no audio coming from phone.
I try snapshot connection state no result.

**Comment by cheebeez** [comment]
As far as I understand, Android 13 beta is only available on Google Pixel 4+ phones.

**Comment by TuupleMasterAndroid** [comment]
As soon as the stream is loaded, the status changes, so you can display any progress bar based on that.

**can you give us some code or idea how implement waiting screen or buffering screen**
