### ISSUE TITLE
Cover artist  dinamic in screen Blocked

### ISSUE THREAD

**Issue by fabricioguedeshotmail** [cheebeez/radio_player#27]
How to call an event to update the dynamic cover by calling an api that brings the artist's cover, is it possible? The cover is not in the metada but comes from an api?

**Comment by cheebeez** [comment]
To display album art from iTunes, use: **itunesArtworkParser(true);**

To utilize metadata from the API, first call: **ignoreIcyMetadata();** Then, when needed, set the metadata using: **setCustomMetadata([artist_string, track_string, url_string]);**

**Comment by fabricioguedeshotmail** [comment]
Thank You!
