### ISSUE TITLE
does not play

### ISSUE THREAD

**Issue by freduss** [cheebeez/radio_player#30]
at the time of pressing the play icon, it does not play I will give you the code that I have written

import 'package:flutter/material.dart';
import 'package:radio_player/radio_player.dart';

class Play extends StatefulWidget {
  const Play({
    Key? key,
    required this.title,
  }) : super(key: key);

  final String title;

  @override
  State<Play> createState() => _PlayState();
}

class _PlayState extends State<Play> {
  final RadioPlayer _radioPlayer = RadioPlayer();
  bool isPlaying = false;
  List<String>? metadata;

  @override
  void initState() {
    super.initState();
    initRadioPlayer();
  }

  void initRadioPlayer() {
    _radioPlayer.setChannel(
      title: 'RadiOriza',
      url: 'https://tv.radiohosting.online:2020/AudioPlayer/9800',
    );

    _radioPlayer.stateStream.listen((event) {
      setState(() {
        isPlaying = event;
      });
    });

    _radioPlayer.metadataStream.listen((event) {
      setState(() {
        metadata= event;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          isPlaying ? _radioPlayer.pause() : _radioPlayer.play();
        },tooltip: 'play',
        child: Icon(
          isPlaying? Icons.pause_rounded: Icons.play_arrow_rounded,
        ),
      ),
    );
  }
}

![Captura](https://user-images.githubusercontent.com/70664500/176780539-a08becf9-6503-4c8f-83cd-717251ca64a1.PNG)

**Comment by cheebeez** [comment]
I think it's because you're using the web player instead of using the streaming url.
