### ISSUE TITLE
Fetch Album Art from Shoutcast & Icecast

### ISSUE THREAD

**Issue by PoerOne** [cheebeez/radio_player#5]
Hi, how can fetch album art from shotcast or icecast server?
Can't get album art if my server is shoutcast or icecast.
Tks

**Comment by cheebeez** [comment]
Hi, I need a stream URL

**Comment by cheebeez** [comment]
`ICY: title="MARCELL - TAKKAN TERGANTI", url="null", rawMetadata.length="40"`
As you can see, your server returns URL = null.

**Comment by PoerOne** [comment]
So, what I need to be adjust from my server?

**Comment by cheebeez** [comment]
ICY metadata should contain a link to the image.
You can compile the radio_player example app it contains a stream with correct artwork url.

**Comment by PoerOne** [comment]
Thanks... 
Work fine now..
