### ISSUE TITLE
Album art in notification does not update on Android 13 - Solution (version 1.0.1)

### ISSUE THREAD

**Issue by owusukasante** [cheebeez/radio_player#9]
I realised that the album art does not update on Android 13 in version 1.0.1. After a little digging, I found that the **getCurrentLargeIcon** method in the RadioPlayerService.kt always returns the defaultArtwork as seen below

```
override fun getCurrentLargeIcon(player: Player, callback: BitmapCallback): Bitmap? {
                metadataArtwork = downloadImage(currentMetadata?.get(2))

                metadataArtwork?.let { callback.onBitmap(it) }
                return  defaultArtwork;
       }
```

Changing it to the following solves the problem

```
override fun getCurrentLargeIcon(player: Player, callback: BitmapCallback): Bitmap? {
                metadataArtwork = downloadImage(currentMetadata?.get(2))

                metadataArtwork?.let { callback.onBitmap(it) }
                return if(metadataArtwork == null) defaultArtwork else metadataArtwork;
            }
```

**Comment by cheebeez** [comment]
Could you post your streaming url for testing, I'll remove the link after I copy it.
Thank you.

**Comment by cheebeez** [comment]
Thank you, I will fix it asap.

**Comment by owusukasante** [comment]
> Thank you, I will fix it asap.

You're welcome man. Really great work. Thank you!!!
